### ISSUE TITLE
[SOLVED ] Scripts to create tables on hasura/postgres

### ISSUE THREAD

**Issue by Tonybsilva-dev** [tgmarinho/members#2]
Seria interessante por no SQL o script para gerar as tables do jeito que foi demonstrado no vídeo, grato desde ja

**Comment by tgmarinho** [comment]
Create Table:

I don't know how to generate DDL from Hasura with Postgres, it will be the best I can do for you now.

There is only a members table:

![image](https://user-images.githubusercontent.com/380327/121008793-61b5ed80-c761-11eb-8a43-698120de69ee.png)


Create View for GraphQL Aggregation: 

```
CREATE
OR REPLACE VIEW "public"."birthdays_by_month" AS
SELECT
  members.birth,
  members.id,
  members.name,
  members.cellphone,
  members.status,
  date_part('day' :: text, members.birth) AS day,
  date_part('month' :: text, members.birth) AS month
FROM
  members;
```

**Comment by tgmarinho** [comment]
![image](https://user-images.githubusercontent.com/380327/121009513-413a6300-c762-11eb-88a0-ab20256010f4.png)

**Comment by tgmarinho** [comment]
After that create `members` table you may wants populate the table with some data:

Then you can run inside of folder of /members:

```
npm install && node _populate.js
``` 

Will be generated a file:

`SQL_insert_members.sql` with some INSERT SQL scripts, you can copy and past to SQL and run the scripts over there.

![image](https://user-images.githubusercontent.com/380327/121010461-6ed3dc00-c763-11eb-9f13-b6025e15bc64.png)

**Comment by tgmarinho** [comment]
You also will needs create your app in Hasura, host it just for free in Heroku:

And replace your endpoint graphql [here](https://github.com/tgmarinho/members/blob/ce1b4e45fcd1466d26d644d12c9e5d1c31db4bd2/graphql/apollo.js#L120).

It better put in in` .env` file (environment variable file) 

Thanks.

**Comment by tgmarinho** [comment]
reopen to keep listed.
